### ISSUE TITLE
Axis -ACAP kills NodeRed when device IP wrong/unreachable

### ISSUE THREAD

**Issue by mschlgl** [pandosme/node-red-axis-acap#1]
invoking a ACAP status request kills NodeRed when IP address of the device is wrong or device is not reacting:

NodeRed-Log:
>>>
node-red.0 | 2022-06-20 11:34:22.341 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
node-red.0 | 2022-06-20 11:34:21.835 | error | list.forEach is not a function
node-red.0 | 2022-06-20 11:34:21.835 | error | TypeError: list.forEach is not a function at /opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-axis-acap/axis-acap.js:48:13 at /opt/iobroker/iobroker-data/node-red/node_modules/vapix-wrapper/vapix-wrapper.js:334:4 at /opt/iobroker/iobroker-data/node-red/node_modules/vapix-wrapper/vapix-wrapper.js:52:4 at /opt/iobroker/iobroker-data/node-red/node_modules/vapix-wrapper/vapix-digest.js:68:4 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)
node-red.0 | 2022-06-20 11:34:21.834 | error | unhandled promise rejection: list.forEach is not a function
node-red.0 | 2022-06-20 11:34:21.827 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
<<<
Input to the node as catched with debug-node:
>>>
20.6.2022, 11:34:19[node: 1353af5e.773791](http://localhost:1880/#)
msg : Object
object
address: "192.168.254.11"
user: "root"
password: "calhatcam"
aktion: "Start ACAP"
action: "ACAP Status"
acap: "vmd"
_msgid: "cbb3d586c35a32d4"
<<<

Environment:
Ubuntu 20.4 inside WSL; Node 16.15.1 npm 6.14.17
IOBroker 4.0.23 running instance NodeRed 3.3.1; 

see attached flow used
[set Trigger.json.txt](https://github.com/pandosme/node-red-axis-acap/files/8939706/set.Trigger.json.txt)
Intended functionality is to activate VMD ACAP only if specific camera is used as a trigger source.

Since sometimes cameras hang and don't react on CGI requests in such a case node should only throw an error but not kill the system.

BR Markus

**Comment by pandosme** [comment]
Thank you for reporting this.  I will investigate.

**Comment by pandosme** [comment]
Fixed in version 1.2.2.  Update node-red-axis-acap from Node-RED.
